# ชื่อของ Workflow ที่จะแสดงในแท็บ Actions
name: Collect Weather Data Hourly

# กำหนดเงื่อนไขที่จะให้ Workflow นี้ทำงาน
on:
  workflow_dispatch:
  schedule:
    # รัน 4 ครั้งต่อวันตามเวลาประเทศไทย (เช้า, กลางวัน, เย็น, ดึก)
    # รัน 4 ครั้งต่อวันตามเวลาประเทศไทย (08:00, 12:00, 18:00, 00:00)
    # เนื่องจาก GitHub Actions ใช้เวลาตาม UTC เราจึงต้องปรับเวลาให้ตรงกับ UTC
    # ดังนั้นเราจะรันที่ 01:00, 05:00, 11:00, และ 17:00 UTC
    # ซึ่งจะตรงกับ 08:00, 12:00, 18:00, และ 00:00 ตามเวลาประเทศไทย
    
    - cron: '0 1,5,11,17 * * *'

# กำหนด "งาน" ที่จะให้ทำ
jobs:
  collect-data:
    # กำหนดให้ทำงานบนระบบปฏิบัติการเวอร์ชันล่าสุดของ Ubuntu
    runs-on: ubuntu-latest
    # ขั้นตอนการทำงาน (จะรันตามลำดับ)
    steps:
      # ขั้นตอนที่ 1: ดึงโค้ดจาก Repository ของเรามาไว้ในเครื่องเสมือน
      - name: Check out repository code
        uses: actions/checkout@v4

      # ขั้นตอนที่ 2: ตั้งค่าสภาพแวดล้อมของ Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ขั้นตอนที่ 3: ติดตั้งไลบรารีที่จำเป็นจากไฟล์ requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    # =======================================================
    # เพิ่มโค้ดส่วนนี้เข้าไปเพื่อดีบักอย่างละเอียด
      - name: Securely Debug Token Value
        run: |
          TOKEN_VALUE="${{ secrets.TMD_TOKEN }}"
          if [ -z "$TOKEN_VALUE" ]; then
            echo "::error::TMD_TOKEN secret is not set or is empty."
            exit 1
          else
            TOKEN_LENGTH=${#TOKEN_VALUE}
            TOKEN_START=${TOKEN_VALUE:0:5}
            TOKEN_END=${TOKEN_VALUE: -5}
            echo "Token successfully read."
            echo "Token Length: $TOKEN_LENGTH"
            echo "Token Starts With: $TOKEN_START..."
            echo "Token Ends With: ...$TOKEN_END"
          fi
    # =======================================================

      # ขั้นตอนที่ 4: รันสคริปต์ Python ของเรา
      - name: Run weather collection script
        # กำหนด Environment Variables ให้กับสคริปต์ โดยดึงค่ามาจาก Secrets ที่เราตั้งไว้
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TMD_TOKEN: ${{ secrets.TMD_TOKEN }}
          TABLE_NAME: 'Weather' # สามารถใส่ค่าที่ไม่ใช่ข้อมูลลับตรงนี้ได้เลย
        # คำสั่งที่ใช้รัน
        run: python weather_script.py